const NonVegTerms = [
    'beef',
    'chicken',
    'chicken chowmin',
    'pork',
    'lamb',
    'veal',
    'bacon',
    'sausage',
    'ham',
    'turkey',
    'duck',
    'goose',
    'fish',
    'seafood',
    'shrimp',
    'lobster',
    'crab',
    'prawn',
    'scallop',
    'mussels',
    'clams',
    'oyster',
    'anchovy',
    'sardine',
    'salmon',
    'tuna',
    'swordfish',
    'steak',
    'fillet',
    'mince',
    'veal',
    'liver',
    'organ meat',
    'game meat',
    'beef',
    'chicken',
    'pork',
    'lamb',
    'veal',
    'bacon',
    'sausage',
    'ham',
    'turkey',
    'duck',
    'goose',
    'quail',
    'venison',
    'rabbit',
    'bison',
    'boar',
    'pheasant',
    'partridge',
    'squab',
    'trout',
    'cod',
    'bass',
    'catfish',
    'perch',
    'sole',
    'halibut',
    'haddock',
    'mahi-mahi',
    'tilapia',
    'sushi',
    'sashimi',
    'ceviche',
    'calamari',
    'octopus',
    'cuttlefish',
    'clam chowder',
    'escargot',
    'frog legs',
    'caviar',
    'roe',
    'crab legs',
    'soft-shell crab',
    'lobster tail',
    'shrimp scampi',
    'oyster stew',
    'mussels marinara',
    'anchovy paste',
    'sardine sandwich',
    'salmon steak',
    'tuna salad',
    'swordfish kebabs',
    'beef steak',
    'filet mignon',
    'ground beef',
    'lamb chops',
    'pork ribs',
    'veal cutlet',
    'bacon-wrapped',
    'sausage links',
    'ham sandwich',
    'turkey burger',
    'duck confit',
    'goose liver pâté',
    'quail eggs',
    'venison jerky',
    'rabbit stew',
    'bison burger',
    'wild boar sausage',
    'pheasant curry',
    'partridge pie',
    'squab roast',
    'trout fillet',
    'cod liver oil',
    'bass fillet',
    'catfish nuggets',
    'perch sandwich',
    'sole meunière',
    'halibut steak',
    'haddock fish and chips',
    'mahi-mahi tacos',
    'tilapia fillet',
    'sushi roll',
    'sashimi platter',
    'ceviche bowl',
    'calamari rings',
    'octopus salad',
    'cuttlefish ink pasta',
    'clam chowder soup',
    'escargot dish',
    'frog legs sautéed',
    'caviar blini',
    'roe sushi',
    'crab legs boil',
    'soft-shell crab sandwich',
    'lobster tail buttered',
    'shrimp scampi pasta',
    'oyster stew pot',
    'mussels marinara pot',
    'anchovy paste tube',
    'sardine sandwich spread',
    'salmon steak grilled',
    'tuna salad sandwich',
    'swordfish kebabs skewered',
    'surf and turf',
    'egg',
    'Machh',
    'Mangsho',
    'Kosha Mangsho',
    'Ilish',
    'Chingri',
    'Kakra',
    'Bhetki',
    'Rui',
    'Katla',
    'Koi',
    'Shorshe Maach',
    'Doi Maach',
    'Murgi',
    'Kosha Murgi',
    'Rezala',
    'Kosha Mangsho',
    'Kochu Pata Diye Murgi',
    'Chitol',
    'Pabda',
    'Dim',
    'Panta Bhat with Ilish',
  'Shutki',
  'Kalaadi',
  'Macher Jhol',
  'Bhapa Ilish',
  'Morich Murgi',
  'Kosha Paturi',
  'Bhapa Chingri',
  'Rui Macher Kalia',
  'Panta Ilish',
  'Murgir Korma',
  'Chitol Macher Muitha',
  'Ilish Bhapa',
  'Shorshe Chingri',
  'Mutton Kalia',
  'Pabda Macher Shorshe Jhal',
  'Dimer Devil',
  'Murgir Dum',
  'Mutton Biryani',
  'Kosha Prawn',
  'Onion',
  'Garlic',
  'Peyaj',
  'Roshun',
  'Maas',
  'Maans',
  'Machli',
  'Machchi',
  'Murga',
  'Murgi',
  'Peyaj',
  'Lahsoon',
  'Anda',
  'Omlet',
  'Egg Fry',
  'Egg Curry',
  'Dimer Jhol',
  'Dimer Kaliya',
];

module.exports = NonVegTerms;